---
- name: Prepare
  hosts: all
  gather_facts: false
  tasks:
    - name: Make sure python3 is installed
      package:
        name: python3
        state: present
      become: true
      register: prepare_python_install
      until: prepare_python_install is not failed
      retries: 5
