#!/usr/bin/env bash

set -e -o pipefail      # exit if there are any errors
export PATH=/usr/local/bin:$PATH

env=$1
echo "********************* 20-install-php *********************"
echo "\$env: $env"

dnf install -y lsphp82 lsphp82-common \
    lsphp82-bcmath \
    lsphp82-gd \
    lsphp82-intl \
    lsphp82-process \
    lsphp82-mbstring \
    lsphp82-pecl-memcached \
    lsphp82-mysqlnd \
    lsphp82-opcache \
    lsphp82-pdo \
    lsphp82-imap \
    lsphp82-sodium \
    lsphp82-soap \
    lsphp82-xml \
    lsphp82-zip


cd /tmp
curl -sS https://getcomposer.org/installer | /usr/local/lsws/lsphp82/bin/php
mv composer.phar /usr/local/bin/composer
ln -s /usr/local/bin/composer /usr/bin/composer
