#!/usr/bin/env bash

set -e -o pipefail      # exit if there are any errors
export PATH=/usr/local/bin:$PATH

echo "********************* 30-configure-lsws *********************"

rm -rf /usr/local/lsws/conf
ln -s /mnt/efs/lsws/conf /usr/local/lsws/conf
mv /usr/local/lsws/lsphp74/bin/lsphp /usr/local/lsws/lsphp74/bin/lsphp74
mv /usr/local/lsws/lsphp82/bin/lsphp /usr/local/lsws/lsphp74/bin/lsphp82

ln -s /var/www/iskconnews.org /usr/local/lsws/prod.iskconnews.org
ln -s /var/www/iskconnews.org /usr/local/lsws/origin.iskconnews.org
ln -s /var/www/phpMyAdmin /usr/local/lsws/pma.iskconnews.org

systemctl enable lsws
systemctl daemon-reload
#systemctl restart lsws
