#!/usr/bin/env bash

set -e -o pipefail      # exit if there are any errors
export PATH=/usr/local/bin:$PATH


echo "********************* 30-install-fstab *********************"

mkdir -p /mnt/efs
rm -rf /var/www

cat <<EOF >> /etc/fstab
# inews efs
fs-ccb95e4d.efs.us-east-1.amazonaws.com:/ /mnt/efs nfs4 nfsvers=4.1,rsize=1048576,wsize=1048576,hard,timeo=600,retrans=2,noresvport 0 2
EOF

mount -a
ln -s /mnt/efs/www /var/www

systemctl daemon-reload
