#!/usr/bin/env bash

set -e -o pipefail      # exit if there are any errors
export PATH=/usr/local/bin:$PATH

echo "********************* 40-install-awscli *********************"

curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
unzip awscliv2.zip
./aws/install
rm -rf aws awscliv2.zip
/usr/local/bin/aws --version
