#!/usr/bin/env bash

set -e -o pipefail      # exit if there are any errors
export PATH=/usr/local/bin:$PATH

env=$1
echo "********************* 75-install-extras-ec2-user *********************"
echo "\$env: $env"

git --git-dir="$HOME/.dotfiles/.git" --work-tree="$HOME" reset --hard

echo "****************************************************************"
echo "***************************** DONE *****************************"
echo "****************************************************************"
